# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CD with Maven

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: maven
      - name: Build and deploy
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          cd ~/library
          git pull origin master
          mvn clean package
      - name: Copy WAR package to Tomcat webapps directory
        run: scp target/*.war ${{ secrets.USERNAME }}@{{ secrets.HOST }}:/usr/local/tomcat/webapps
      - name: Restart Tomcat server
        run: ssh ${{ secrets.USERNAME }}@{{ secrets.HOST }} "sudo systemctl restart tomcat"
